version: '3'
services:
  nginx1:
    image: nginx:1.20
    container_name: nginx1
    volumes:
      - ./nginx1.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
